In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\cm617yh\appdata\local\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\cm617yh\appdata\local\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cm617yh\appdata\local\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\cm617yh\appdata\local\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cm617yh\appdata\local\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\cm617yh\appdata\local\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd
import numpy as np

In [2]:
x=[1,2,3,4,5]
pd.Series(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
pd.Series([11,22,33,44,55])

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [4]:
pd.Series([11,22,33,44,55],dtype=float)

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
dtype: float64

In [5]:
df=pd.Series([11,22,33,44,55],["a","b","c","d","e"],dtype=float)
df1=pd.Series([110,220,330,440,550],["a","b","c","d","e"],dtype=float)

In [6]:
df

a    11.0
b    22.0
c    33.0
d    44.0
e    55.0
dtype: float64

In [7]:
# df[0]
df["a"]

np.float64(11.0)

In [8]:
df+df1
df-df1

a    -99.0
b   -198.0
c   -297.0
d   -396.0
e   -495.0
dtype: float64

In [9]:
#DataFrame

dict1={"Name":["Aniket","Nilesh","Anup","Aakash","Devendra","Maithli","Rasika","Surbhi","Sakshi","Sakshi"],
      "Age":[29,28,19,22,24,24,26,27,20,"20"],
      "City":["Itarasi","Nagpur","Nagpur","Ashti","Butibori","Nagpur","Kamleshwar","Gadchiroli","Nagpur","Nagpur"],
      "Salary":[35000,34000,23000,34000,34000,45000,55000,34000,23000,23000]}

In [10]:
pd.DataFrame([1,2,3,4])

   0
0  1
1  2
2  3
3  4

In [11]:
pd.DataFrame(df)

      0
a  11.0
b  22.0
c  33.0
d  44.0
e  55.0

In [12]:
df=pd.DataFrame(dict1)

In [13]:
df.head()

       Name Age      City  Salary
0    Aniket  29   Itarasi   35000
1    Nilesh  28    Nagpur   34000
2      Anup  19    Nagpur   23000
3    Aakash  22     Ashti   34000
4  Devendra  24  Butibori   34000

In [14]:
df.tail()

      Name Age        City  Salary
5  Maithli  24      Nagpur   45000
6   Rasika  26  Kamleshwar   55000
7   Surbhi  27  Gadchiroli   34000
8   Sakshi  20      Nagpur   23000
9   Sakshi  20      Nagpur   23000

In [15]:
df["Name"]=df["Name"].str.lower()

In [16]:
#duplicates
#missing value
#inconsistent data
#outlier

df.duplicated().sum()

np.int64(0)

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
df.dtypes

Name      object
Age       object
City      object
Salary     int64
dtype: object

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     object
 2   City    10 non-null     object
 3   Salary  10 non-null     int64
dtypes: int64(1), object(3)
memory usage: 452.0+ bytes

In [20]:
df.Age.unique()

array([29, 28, 19, 22, 24, 26, 27, 20, '20'], dtype=object)

In [21]:
df["Age"]=df["Age"].astype(int)

In [22]:
df.dtypes

Name      object
Age        int64
City      object
Salary     int64
dtype: object

In [23]:
df.columns

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

In [24]:
df["Bonus"]=df["Salary"]*0.2

In [25]:
df

       Name  Age        City  Salary    Bonus
0    aniket   29     Itarasi   35000   7000.0
1    nilesh   28      Nagpur   34000   6800.0
2      anup   19      Nagpur   23000   4600.0
3    aakash   22       Ashti   34000   6800.0
4  devendra   24    Butibori   34000   6800.0
5   maithli   24      Nagpur   45000   9000.0
6    rasika   26  Kamleshwar   55000  11000.0
7    surbhi   27  Gadchiroli   34000   6800.0
8    sakshi   20      Nagpur   23000   4600.0
9    sakshi   20      Nagpur   23000   4600.0

In [26]:
df.drop(["Bonus"],axis=1,inplace=True)

In [27]:
df

       Name  Age        City  Salary
0    aniket   29     Itarasi   35000
1    nilesh   28      Nagpur   34000
2      anup   19      Nagpur   23000
3    aakash   22       Ashti   34000
4  devendra   24    Butibori   34000
5   maithli   24      Nagpur   45000
6    rasika   26  Kamleshwar   55000
7    surbhi   27  Gadchiroli   34000
8    sakshi   20      Nagpur   23000
9    sakshi   20      Nagpur   23000

In [28]:
#DataFrame

dict1={"Name":["Aniket","Nilesh",np.nan,"Aakash","Devendra",np.nan,"Rasika","Surbhi","Sakshi","Sakshi"],
      "Age":[29,28,19,22,24,np.nan,26,27,20,20],
      "City":["Itarasi","Nagpur","Nagpur","Ashti",np.nan,"Nagpur","Kamleshwar","Gadchiroli","Nagpur","Nagpur"],
      "Salary":[35000,34000,None,34000,34000,45000,55000,34000,23000,23000]}

In [29]:
df=pd.DataFrame(dict1)

In [30]:
df.isna().sum()

Name      2
Age       1
City      1
Salary    1
dtype: int64

In [108]:
df.fillna(0)

       Name   Age        City   Salary
0    Aniket  29.0     Itarasi  35000.0
1    Nilesh  28.0      Nagpur  34000.0
2         0  19.0      Nagpur      0.0
3    Aakash  22.0       Ashti  34000.0
4  Devendra  24.0           0  34000.0
5         0   0.0      Nagpur  45000.0
6    Rasika  26.0  Kamleshwar  55000.0
7    Surbhi  27.0  Gadchiroli  34000.0
8    Sakshi  20.0      Nagpur  23000.0
9    Sakshi  20.0      Nagpur  23000.0

In [111]:
df.fillna(method="ffill")
df.fillna(method="bfill")
df.interpolate()

C:\Users\CM617YH\AppData\Local\Temp\ipykernel_57704\2987474268.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")
C:\Users\CM617YH\AppData\Local\Temp\ipykernel_57704\2987474268.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")
C:\Users\CM617YH\AppData\Local\Temp\ipykernel_57704\2987474268.py:3: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate()

       Name   Age        City   Salary
0    Aniket  29.0     Itarasi  35000.0
1    Nilesh  28.0      Nagpur  34000.0
2       NaN  19.0      Nagpur  34000.0
3    Aakash  22.0       Ashti  34000.0
4  Devendra  24.0         NaN  34000.0
5       NaN  25.0      Nagpur  45000.0
6    Rasika  26.0  Kamleshwar  55000.0
7    Surbhi  27.0  Gadchiroli  34000.0
8    Sakshi  20.0      Nagpur  23000.0
9    Sakshi  20.0      Nagpur  23000.0

In [120]:
df.Name.fillna(df.Name.mode()[0])
df.Age.fillna(round(df.Age.mean(),1))
df.Salary.fillna(round(df.Salary.mean(),1))
df.City.fillna(df.City.mode()[0])

0       Itarasi
1        Nagpur
2        Nagpur
3         Ashti
4        Nagpur
5        Nagpur
6    Kamleshwar
7    Gadchiroli
8        Nagpur
9        Nagpur
Name: City, dtype: object

In [121]:
df.Name.replace(np.nan,"Unknown")

0      Aniket
1      Nilesh
2     Unknown
3      Aakash
4    Devendra
5     Unknown
6      Rasika
7      Surbhi
8      Sakshi
9      Sakshi
Name: Name, dtype: object

In [122]:
df.dropna()

     Name   Age        City   Salary
0  Aniket  29.0     Itarasi  35000.0
1  Nilesh  28.0      Nagpur  34000.0
3  Aakash  22.0       Ashti  34000.0
6  Rasika  26.0  Kamleshwar  55000.0
7  Surbhi  27.0  Gadchiroli  34000.0
8  Sakshi  20.0      Nagpur  23000.0
9  Sakshi  20.0      Nagpur  23000.0

In [128]:
df=pd.read_excel(r"C:\Users\CM617YH\OneDrive - EY\Desktop\study\data\Online Retail.xlsx",nrows=10000)

In [129]:
df.head()
df.size
df.shape

(10000, 8)

In [133]:
df1=pd.read_csv(r"C:\Users\CM617YH\OneDrive - EY\Desktop\study\data\Sample - Superstore.csv",encoding='latin1')

In [135]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: sqlalchemy in c:\users\cm617yh\appdata\local\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\cm617yh\appdata\local\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\cm617yh\appdata\local\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [137]:
from sqlalchemy import create_engine
import pymysql # Required for the connection string

# Database connection details
DB_USER = 'root'
DB_PASSWORD = '1234'
DB_HOST = 'localhost' # Or your database IP address
DB_PORT = 3306
DB_NAME = 'sakila'

# Create the connection string and engine
# The 'mysql+pymysql://' part specifies the dialect and driver
connection_string = f'mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
engine = create_engine(connection_string)

# SQL query to select data
sql_query = 'SELECT * FROM actor'

# Read the SQL query results directly into a pandas DataFrame
df = pd.read_sql_query(sql_query, engine)

# Display the first few rows of the DataFrame
print(df.head())

# Close the engine connection (optional, as pandas manages it within the function)
engine.dispose()

   actor_id first_name     last_name         last_update
0         1   PENELOPE       GUINESS 2006-02-15 04:34:33
1         2       NICK      WAHLBERG 2006-02-15 04:34:33
2         3         ED         CHASE 2006-02-15 04:34:33
3         4   JENNIFER         DAVIS 2006-02-15 04:34:33
4         5     JOHNNY  LOLLOBRIGIDA 2006-02-15 04:34:33

In [139]:
df1.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Percentage,Unnamed: 22,Unnamed: 23
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0,NaN,NaN
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0,NaN,NaN
2,3,CA-2017-138688,12-06-2017,16-06-2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0,NaN,NaN
3,4,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,45,NaN,NaN
4,5,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,20,NaN,NaN

In [144]:
df1["Country"]

0       United States
1       United States
2       United States
3       United States
4       United States
            ...
9989    United States
9990    United States
9991    United States
9992    United States
9993    United States
Name: Country, Length: 9994, dtype: object

In [34]:
df=pd.read_csv(r"C:\Users\CM617YH\OneDrive - EY\Desktop\study\data\Sample - Superstore.csv",encoding='latin1')

In [35]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Percentage,Unnamed: 22,Unnamed: 23
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0,NaN,NaN
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0,NaN,NaN
2,3,CA-2017-138688,12-06-2017,16-06-2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0,NaN,NaN
3,4,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,45,NaN,NaN
4,5,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,20,NaN,NaN

In [36]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Percentage',
       'Unnamed: 22', 'Unnamed: 23'],
      dtype='object')

In [37]:
df[df["Region"]=="East"]
df[df["Segment"]=="Consumer"]
df[df["Sales"]>=150]
df[(df["Sales"]>=150) & (df["Region"]=="East")]
df[(df["Sales"]>=150) | (df["Region"]=="East")]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Percentage,Unnamed: 22,Unnamed: 23
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0,NaN,NaN
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0,NaN,NaN
3,4,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,45,NaN,NaN
7,8,CA-2015-115812,09-06-2015,14-06-2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152,20,NaN,NaN
10,11,CA-2015-115812,09-06-2015,14-06-2015,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092,20,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9984,9985,CA-2016-100251,17-05-2016,23-05-2016,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,Office Supplies,Labels,Self-Adhesive Removable Labels,31.5000,10,0.00,15.1200,0,NaN,NaN
9985,9986,CA-2016-100251,17-05-2016,23-05-2016,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,55.6000,4,0.00,16.1240,0,NaN,NaN
9988,9989,CA-2018-163629,17-11-2018,21-11-2018,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,Technology,Phones,Panasonic KX - TS880B Telephone,206.1000,5,0.00,55.6470,0,NaN,NaN
9991,9992,CA-2018-121258,26-02-2018,03-03-2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,20,NaN,NaN
9993,9994,CA-2018-119914,04-05-2018,09-05-2018,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,0,NaN,NaN

In [38]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Percentage,Unnamed: 22,Unnamed: 23
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0,NaN,NaN
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0,NaN,NaN
2,3,CA-2017-138688,12-06-2017,16-06-2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0,NaN,NaN
3,4,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,45,NaN,NaN
4,5,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,20,NaN,NaN

In [39]:
df.loc[:]
df.loc[0:5]
df.loc[:5,["Segment"]]
df.loc[:5,["Segment","Region"]]
df.loc[:5,"Segment":"Region"]

     Segment        Country             City       State  Postal Code Region
0   Consumer  United States        Henderson    Kentucky      42420.0  South
1   Consumer  United States        Henderson    Kentucky      42420.0  South
2  Corporate  United States      Los Angeles  California      90036.0   West
3   Consumer  United States  Fort Lauderdale     Florida      33311.0  South
4   Consumer  United States  Fort Lauderdale     Florida      33311.0  South
5   Consumer  United States      Los Angeles  California      90032.0   West

In [40]:
df.iloc[:]
df.iloc[1:5]
df.iloc[1:5,4]
df.iloc[1:5,4:10]
df.iloc[1:5,[2,4,5]]

   Order Date       Ship Mode Customer ID
1  08-11-2017    Second Class    CG-12520
2  12-06-2017    Second Class    DV-13045
3  11-10-2016  Standard Class    SO-20335
4  11-10-2016  Standard Class    SO-20335

In [41]:
df.sort_values("Region",ascending=False)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Percentage,Unnamed: 22,Unnamed: 23
9993,9994,CA-2018-119914,04-05-2018,09-05-2018,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480,0,NaN,NaN
6213,6214,CA-2018-149944,12-11-2018,16-11-2018,Second Class,MB-17305,Maria Bertelson,Consumer,United States,Longview,...,Office Supplies,Appliances,Fellowes Superior 10 Outlet Split Surge Protector,76.120,2,0.0,22.0748,0,NaN,NaN
6243,6244,CA-2017-165561,24-11-2017,28-11-2017,Standard Class,CR-12580,Clay Rozendal,Home Office,United States,Bellevue,...,Office Supplies,Supplies,"Elite 5"" Scissors",25.350,3,0.0,7.6050,0,NaN,NaN
2613,2614,CA-2017-137204,28-04-2017,05-05-2017,Standard Class,BO-11350,Bill Overfelt,Corporate,United States,Los Angeles,...,Furniture,Chairs,"Global Stack Chair without Arms, Black",41.568,2,0.2,2.5980,20,NaN,NaN
2614,2615,CA-2015-147298,26-04-2015,03-05-2015,Standard Class,AG-10300,Aleksandra Gannaway,Corporate,United States,Los Angeles,...,Furniture,Chairs,Bevis Steel Folding Chairs,230.280,3,0.2,23.0280,20,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3160,3161,US-2015-150924,12-09-2015,16-09-2015,Second Class,PT-19090,Pete Takahito,Consumer,United States,Houston,...,Office Supplies,Binders,Wilson Jones Impact Binders,5.180,5,0.8,-8.0290,80,NaN,NaN
3167,3168,CA-2017-146682,29-10-2017,31-10-2017,First Class,KW-16435,Katrina Willman,Consumer,United States,Lansing,...,Furniture,Furnishings,Electrix 20W Halogen Replacement Bulb for Zoom...,67.000,5,0.0,32.1600,0,NaN,NaN
3171,3172,US-2017-133879,21-03-2017,28-03-2017,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Chicago,...,Office Supplies,Binders,Avery Durable Slant Ring Binders,3.168,2,0.8,-4.7520,80,NaN,NaN
3172,3173,US-2017-133879,21-03-2017,28-03-2017,Standard Class,KT-16465,Kean Takahito,Consumer,United States,Chicago,...,Furniture,Chairs,"Global Airflow Leather Mesh Back Chair, Black",528.430,5,0.3,0.0000,30,NaN,NaN
7073,7074,CA-2017-112256,23-07-2017,28-07-2017,Standard Class,CK-12205,Chloris Kastensmidt,Consumer,United States,Mcallen,...,Office Supplies,Art,Boston 1645 Deluxe Heavier-Duty Electric Penci...,175.920,5,0.2,15.3930,20,NaN,NaN

In [43]:
grp=df.groupby(df["Region"])

In [44]:
grp.groups

{'Central': [14, 15, 16, 21, 22, 34, 35, 36, 37, 38, 39, 40, 41, 44, 45, 46, 49, 50, 51, 52, 66, 71, 75, 76, 77, 78, 84, 86, 87, 88, 92, 93, 94, 98, 99, 100, 101, 102, 109, 111, 112, 124, 125, 144, 147, 148, 149, 150, 158, 159, 164, 165, 166, 167, 168, 169, 170, 174, 175, 176, 180, 181, 187, 188, 203, 206, 207, 208, 209, 210, 211, 225, 226, 227, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 254, 255, 256, 257, 261, 262, 263, 264, 280, 281, 303, 305, 344, 370, ...], 'East': [23, 27, 28, 29, 30, 31, 32, 33, 47, 48, 53, 54, 55, 56, 57, 58, 59, 60, 61, 70, 96, 110, 113, 114, 115, 116, 119, 120, 121, 122, 123, 130, 131, 132, 140, 146, 161, 177, 178, 179, 185, 189, 190, 191, 192, 193, 195, 196, 197, 198, 199, 200, 212, 213, 214, 215, 216, 219, 220, 221, 222, 223, 224, 252, 253, 258, 259, 260, 267, 268, 269, 276, 277, 278, 279, 289, 290, 291, 292, 298, 299, 300, 301, 302, 304, 306, 307, 313, 316, 317, 318, 319, 320, 321, 326, 327, 328, 329, 330, 331, ...], 'South': [0, 1, 3, 4, 12, 43, 69, 72, 73, 74, 79, 80, 83, 85, 106, 107, 108, 118, 182, 183, 184, 204, 228, 229, 230, 231, 232, 233, 234, 235, 266, 286, 287, 288, 308, 314, 315, 325, 358, 359, 360, 384, 385, 402, 403, 418, 424, 429, 430, 431, 432, 434, 435, 494, 495, 506, 507, 508, 509, 526, 527, 533, 534, 538, 539, 552, 555, 561, 562, 586, 587, 602, 603, 604, 605, 606, 633, 634, 635, 664, 683, 684, 685, 686, 687, 689, 690, 691, 704, 705, 706, 711, 724, 755, 761, 763, 764, 765, 766, 767, ...], 'West': [2, 5, 6, 7, 8, 9, 10, 11, 13, 17, 18, 19, 20, 24, 25, 26, 42, 62, 63, 64, 65, 67, 68, 81, 82, 89, 90, 91, 95, 97, 103, 104, 105, 117, 126, 127, 128, 129, 133, 134, 135, 136, 137, 138, 139, 141, 142, 143, 145, 151, 152, 153, 154, 155, 156, 157, 160, 162, 163, 171, 172, 173, 186, 194, 201, 202, 205, 217, 218, 236, 249, 250, 251, 265, 270, 271, 272, 273, 274, 275, 282, 283, 284, 285, 293, 294, 295, 296, 297, 309, 310, 311, 312, 322, 323, 324, 334, 335, 336, 337, ...]}

In [49]:
df.groupby(df["Region"])["Row ID"].count()

Region
Central    2323
East       2848
South      1620
West       3203
Name: Row ID, dtype: int64

In [50]:
df.groupby(df["Region"])["Sales"].sum()

Region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: Sales, dtype: float64

In [52]:
df.groupby(df["Region"])["Sales"].mean()

Region
Central    215.772661
East       238.336110
South      241.803645
West       226.493233
Name: Sales, dtype: float64

In [53]:
df.groupby(df["Region"])["Sales"].max()

Region
Central    17499.950
East       11199.968
South      22638.480
West       13999.960
Name: Sales, dtype: float64

In [54]:
df.groupby(df["Region"])["Sales"].min()

Region
Central    0.444
East       0.852
South      1.167
West       0.990
Name: Sales, dtype: float64

In [65]:
print(df.groupby(["Region","Segment"])["Sales"].min())

Region   Segment
Central  Consumer       0.444
         Corporate      0.556
         Home Office    1.408
East     Consumer       0.852
         Corporate      1.188
         Home Office    1.640
South    Consumer       1.344
         Corporate      1.167
         Home Office    2.816
West     Consumer       1.080
         Corporate      1.188
         Home Office    0.990
Name: Sales, dtype: float64

In [67]:
print(df.groupby(["Region","Segment"])[["Sales","Profit"]].min())

                     Sales     Profit
Region  Segment
Central Consumer     0.444 -3701.8928
        Corporate    0.556 -2929.4845
        Home Office  1.408 -1143.8910
East    Consumer     0.852 -6599.9780
        Corporate    1.188  -950.4000
        Home Office  1.640  -760.9800
South   Consumer     1.344 -1862.3124
        Corporate    1.167 -3839.9904
        Home Office  2.816 -1811.0784
West    Consumer     1.080  -786.7440
        Corporate    1.188  -465.5680
        Home Office  0.990 -3399.9800

In [72]:
df.groupby(df["Region"])["Sales"].agg({"min",'max',"sum","mean"})

               max          sum        mean    min
Region
Central  17499.950  501239.8908  215.772661  0.444
East     11199.968  678781.2400  238.336110  0.852
South    22638.480  391721.9050  241.803645  1.167
West     13999.960  725457.8245  226.493233  0.990

In [73]:
df1=pd.DataFrame({"ID":[1,2,3,4,5],
                 "Product":["A","B","C","D","E"]})

df2=pd.DataFrame({"ID":[1,2,5,6,7],
                 "Price":[10,20,30,40,50]})

In [75]:
pd.concat([df1,df2])
pd.concat([df1,df2],axis=1)

   ID Product  ID  Price
0   1       A   1     10
1   2       B   2     20
2   3       C   5     30
3   4       D   6     40
4   5       E   7     50

In [77]:
df1.merge(df2,on="ID")

   ID Product  Price
0   1       A     10
1   2       B     20
2   5       E     30

In [78]:
df1.merge(df2,on="ID",how="left")

   ID Product  Price
0   1       A   10.0
1   2       B   20.0
2   3       C    NaN
3   4       D    NaN
4   5       E   30.0

In [79]:
df1.merge(df2,on="ID",how="right")

   ID Product  Price
0   1       A     10
1   2       B     20
2   5       E     30
3   6     NaN     40
4   7     NaN     50

In [80]:
df1.merge(df2,on="ID",how="outer")

   ID Product  Price
0   1       A   10.0
1   2       B   20.0
2   3       C    NaN
3   4       D    NaN
4   5       E   30.0
5   6     NaN   40.0
6   7     NaN   50.0

In [82]:
df2.rename(columns={"Price":"Prices"})

   ID  Prices
0   1      10
1   2      20
2   5      30
3   6      40
4   7      50

In [83]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Percentage,Unnamed: 22,Unnamed: 23
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0,NaN,NaN
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0,NaN,NaN
2,3,CA-2017-138688,12-06-2017,16-06-2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0,NaN,NaN
3,4,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,45,NaN,NaN
4,5,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,20,NaN,NaN

In [84]:
df["Ship Mode"].value_counts()

Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

In [89]:
df2["Bonus"]=df2["Price"].apply(lambda x:x*1.1)

In [90]:
df2

   ID  Price  Bonus
0   1   11.0   12.1
1   2   22.0   24.2
2   5   33.0   36.3
3   6   44.0   48.4
4   7   55.0   60.5

In [92]:
def cat(x):
    if x<=10:
        return "Low"
    elif x>10 and x<=30:
        return "Medium"
    else:
        return "High"
df2['Price_Category']=df2["Price"].apply(cat)

In [93]:
df2

   ID  Price  Bonus Price_Category
0   1   11.0   12.1         Medium
1   2   22.0   24.2         Medium
2   5   33.0   36.3           High
3   6   44.0   48.4           High
4   7   55.0   60.5           High

In [97]:
pd.get_dummies(df2,columns=["Price_Category"],dtype=int,drop_first=True)

   ID  Price  Bonus  Price_Category_Medium
0   1   11.0   12.1                      1
1   2   22.0   24.2                      1
2   5   33.0   36.3                      0
3   6   44.0   48.4                      0
4   7   55.0   60.5                      0

In [98]:
df2.describe()

             ID      Price     Bonus
count  5.000000   5.000000   5.00000
mean   4.200000  33.000000  36.30000
std    2.588436  17.392527  19.13178
min    1.000000  11.000000  12.10000
25%    2.000000  22.000000  24.20000
50%    5.000000  33.000000  36.30000
75%    6.000000  44.000000  48.40000
max    7.000000  55.000000  60.50000

In [100]:
df2["Price_Category"]=df2["Price_Category"].map({"Medium":"M","Low":"L","High":"H"})

In [101]:
df2

   ID  Price  Bonus Price_Category
0   1   11.0   12.1              M
1   2   22.0   24.2              M
2   5   33.0   36.3              H
3   6   44.0   48.4              H
4   7   55.0   60.5              H

In [102]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Percentage,Unnamed: 22,Unnamed: 23
0,1,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0,NaN,NaN
1,2,CA-2017-152156,08-11-2017,11-11-2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0,NaN,NaN
2,3,CA-2017-138688,12-06-2017,16-06-2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0,NaN,NaN
3,4,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,45,NaN,NaN
4,5,US-2016-108966,11-10-2016,18-10-2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,20,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2015-110422,21-01-2015,23-01-2015,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028,20,NaN,NaN
9990,9991,CA-2018-121258,26-02-2018,03-03-2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332,0,NaN,NaN
9991,9992,CA-2018-121258,26-02-2018,03-03-2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932,20,NaN,NaN
9992,9993,CA-2018-121258,26-02-2018,03-03-2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200,0,NaN,NaN
9993,9994,CA-2018-119914,04-05-2018,09-05-2018,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480,0,NaN,NaN

In [104]:
pd.pivot_table(df,values="Sales",index="Segment",aggfunc="mean")

                  Sales
Segment
Consumer     223.733644
Corporate    233.823300
Home Office  240.972041

In [105]:
df2

   ID  Price  Bonus Price_Category
0   1   11.0   12.1              M
1   2   22.0   24.2              M
2   5   33.0   36.3              H
3   6   44.0   48.4              H
4   7   55.0   60.5              H

In [106]:
df2.set_index(["ID"])

    Price  Bonus Price_Category
ID
1    11.0   12.1              M
2    22.0   24.2              M
5    33.0   36.3              H
6    44.0   48.4              H
7    55.0   60.5              H

E commerce Project

In [3]:
!pip install matplotlib seaborn

Collecting matplotlib
  Using cached matplotlib-3.10.8-cp312-cp312-win_amd64.whl.metadata (52 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.62.1-cp312-cp312-win_amd64.whl.metadata (119 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: numpy>=1.23 in c:\users\cm617yh\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.4.1)
Requirement already satisfied: packaging>=20.0 in c:\users\cm617yh\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\cm617yh\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (12.1.1)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\cm617yh\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\cm617yh\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\cm617yh\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cm617yh\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.2->seaborn) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\cm617yh\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Using cached matplotlib-3.10.8-cp312-cp312-win_amd64.whl (8.1 MB)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached contourpy-1.3.3-cp312-cp312-win_amd64.whl (226 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.62.1-cp312-cp312-win_amd64.whl (2.3 MB)
Using cached kiwisolver-1.5.0-cp312-cp312-win_amd64.whl (73 kB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ---------------------------------------- 0/7 [pyparsing]
   ---------------------------------------- 0/7 [pyparsing]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ----------- ---------------------------- 2/7 [fonttools]
   ---------------------- ----------------- 4/7 [contourpy]
   ---------------------- ----------------- 4/7 [contourpy]
   ---------------------- ----------------- 4/7 [contourpy]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------- ----------- 5/7 [matplotlib]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------- ----- 6/7 [seaborn]
   ---------------------------------------- 7/7 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.62.1 kiwisolver-1.5.0 matplotlib-3.10.8 pyparsing-3.3.2 seaborn-0.13.2

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df=pd.read_excel(r"C:\Users\CM617YH\OneDrive - EY\Desktop\study\data\Online Retail.xlsx")

In [6]:
# to check first five records
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
df.shape

(541909, 8)

In [8]:
df.duplicated().sum()

np.int64(5268)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 536641 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    536641 non-null  object
 1   StockCode    536641 non-null  object
 2   Description  535187 non-null  object
 3   Quantity     536641 non-null  int64
 4   InvoiceDate  536641 non-null  datetime64[ns]
 5   UnitPrice    536641 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      536641 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 36.8+ MB

In [11]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,536641.000000,536641,536641.000000,401604.000000
mean,9.620029,2011-07-04 08:57:06.087421952,4.632656,15281.160818
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 10:52:00,1.250000,13939.000000
50%,3.000000,2011-07-19 14:04:00,2.080000,15145.000000
75%,10.000000,2011-10-18 17:05:00,4.130000,16784.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,219.130156,NaN,97.233118,1714.006089

In [12]:
(df.isna().sum()/df.shape[0])*100

InvoiceNo       0.000000
StockCode       0.000000
Description     0.270945
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     25.163377
Country         0.000000
dtype: float64

In [13]:
df.dropna(subset=["CustomerID"],inplace=True)

In [14]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [15]:
df=df[df["Quantity"]>0]

In [16]:
df.Description.fillna(df.Description.mode()[0],inplace=True)

C:\Users\CM617YH\AppData\Local\Temp\ipykernel_35300\1225544144.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Description.fillna(df.Description.mode()[0],inplace=True)

In [17]:
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [18]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [19]:
df["TotalAmount"]=df["Quantity"]*df["UnitPrice"]

In [28]:
df["CustomerID"]=df["CustomerID"].astype(int)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount,month
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,2010-12

In [21]:
df["month"]=df["InvoiceDate"].dt.to_period("M")

In [22]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount,month
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010-12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010-12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12

In [23]:
#Total Revenue

df["TotalAmount"].sum()

np.float64(8887208.894)

In [25]:
# Top 10 Products

df.groupby("Description")["TotalAmount"].sum().sort_values(ascending=False).head(10)

Description
PAPER CRAFT , LITTLE BIRDIE           168469.60
REGENCY CAKESTAND 3 TIER              142264.75
WHITE HANGING HEART T-LIGHT HOLDER    100392.10
JUMBO BAG RED RETROSPOT                85040.54
MEDIUM CERAMIC TOP STORAGE JAR         81416.73
POSTAGE                                77803.96
PARTY BUNTING                          68785.23
ASSORTED COLOUR BIRD ORNAMENT          56413.03
Manual                                 53419.93
RABBIT NIGHT LIGHT                     51251.24
Name: TotalAmount, dtype: float64

In [29]:
df.groupby("CustomerID")["TotalAmount"].sum().sort_values(ascending=False).head(10)

CustomerID
14646    280206.02
18102    259657.30
17450    194390.79
16446    168472.50
14911    143711.17
12415    124914.53
14156    117210.08
17511     91062.38
16029     80850.84
12346     77183.60
Name: TotalAmount, dtype: float64

In [34]:
# monthly Revenue Trend

df.groupby("month")["TotalAmount"].sum()

month
2010-12     570422.730
2011-01     568101.310
2011-02     446084.920
2011-03     594081.760
2011-04     468374.331
2011-05     677355.150
2011-06     660046.050
2011-07     598962.901
2011-08     644051.040
2011-09     950690.202
2011-10    1035642.450
2011-11    1156205.610
2011-12     517190.440
Freq: M, Name: TotalAmount, dtype: float64

In [35]:
# country wise revenue
df.groupby("Country")["TotalAmount"].sum()

Country
Australia                138453.810
Austria                   10198.680
Bahrain                     548.400
Belgium                   41196.340
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20440.540
Cyprus                    13502.850
Czech Republic              826.740
Denmark                   18955.340
EIRE                     265262.460
European Community         1300.250
Finland                   22546.080
France                   208934.310
Germany                  228678.400
Greece                     4760.520
Iceland                    4310.000
Israel                     7215.840
Italy                     17483.240
Japan                     37416.370
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2725.590
Netherlands              285446.340
Norway                    36165.440
Poland                     7334.650
Portugal                  33375.840
RSA                        1002.310
Saudi Arabia                145.920
Singapore                 21279.290
Spain                     61558.560
Sweden                    38367.830
Switzerland               56443.950
USA                        3580.390
United Arab Emirates       1902.280
United Kingdom          7285024.644
Unspecified                2660.770
Name: TotalAmount, dtype: float64